/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { Fire } from "./Fire";
import { useGLTF } from "@react-three/drei";

import gsap from "gsap";
import { useGSAP } from "@gsap/react";
import { useRef } from "react";
import { ScrollTrigger } from "gsap/ScrollTrigger";

gsap.registerPlugin(useGSAP);
gsap.registerPlugin(ScrollTrigger);

export function Sofa(props: JSX.IntrinsicElements["group"]) {
    const fireRef = useRef(null);
    const fireRef2 = useRef(null);
    useGSAP(
        () => {
            if (!fireRef.current) return;

            gsap.to(fireRef.current.rotation, {
                y: Math.PI * 2,
                duration: 10,
                repeat: -1,
                repeatDelay: 0,
                ease: "power1.inOut",
            });
            gsap.to(fireRef2.current.rotation, {
                y: -Math.PI * 2,
                duration: 10,
                repeat: -1,
                repeatDelay: 0,
                ease: "power1.inOut",
            });
        },
        { dependencies: [fireRef, fireRef2] }
    );

    console.log("this is fire", fireRef.current);

    const { nodes, materials } = useGLTF("/Sofa.glb");
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder004.geometry}
                material={materials["Material.002"]}
                // material={FireMaterial}
                position={[-2.693, -0.305, 0.301]}
                rotation={[-Math.PI, 0.005, -Math.PI]}
                scale={[0.036, 0.07, 0.036]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder006.geometry}
                material={materials["Material.001"]}
                position={[-2.693, -0.307, -0.318]}
                rotation={[-Math.PI, 0.005, -Math.PI]}
                scale={[0.036, 0.07, 0.036]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube009.geometry}
                material={materials["Material.003"]}
                // material={FireMaterial}
                position={[0.463, 0.267, -0.007]}
            />
            <Fire scale={2} position={[0, 0.6, 0]} ref={fireRef} />
            <Fire scale={2} position={[0, 0.6, 0]} ref={fireRef2} />
            {/* <Fire scale={2} position={[0, 0.8, 0]} /> */}
            {/* <Fire scale={2} position={[0, 0.8, 0]} /> */}
        </group>
    );
}

useGLTF.preload("/Sofa.glb");
